name: Merge to Main

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build production image
        run: |
          docker build -t ${GITHUB_REPOSITORY}:latest -f Dockerfile --target production .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        run: |
          docker tag ${GITHUB_REPOSITORY}:latest ghcr.io/${GITHUB_REPOSITORY}:latest
          docker push ghcr.io/${GITHUB_REPOSITORY}:latest

      - name: Deploy to production
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d

      - name: Run health check
        run: |
          # Wait for services to be ready
          sleep 15
          curl -f http://localhost:80/api/health || exit 1
