services:
  test-db:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    tmpfs:
      - /var/lib/postgresql/data

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      - POSTGRES_SERVER=test-db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
      - POSTGRES_PORT=5432
      - SECRET_KEY=test_secret_key
      - FIRST_SUPERUSER=admin@example.com
      - FIRST_SUPERUSER_PASSWORD=admin
      - DOMAIN=localhost
      - FRONTEND_HOST=http://localhost
      - ENVIRONMENT=test
      - BACKEND_CORS_ORIGINS=["http://localhost"]
      - PYTHONPATH=/app
    working_dir: /app
    command: pytest -v --cov=app --cov-report=term-missing
