name: Shared Build

on:
  workflow_call:
    inputs:
      target:
        description: 'Docker build target'
        required: true
        type: string
        default: 'production'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${GITHUB_REPOSITORY}:${{ inputs.target }} -f Dockerfile --target ${{ inputs.target }} .

      - name: Login to GitHub Container Registry
        if: ${{ inputs.target == 'production' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        if: ${{ inputs.target == 'production' }}
        run: |
          docker tag ${GITHUB_REPOSITORY}:${{ inputs.target }} ghcr.io/${GITHUB_REPOSITORY}:${{ inputs.target }}
          docker push ghcr.io/${GITHUB_REPOSITORY}:${{ inputs.target }}
