name: Feature Branch Push (v2)

on:
  push:
    branches:
      - feat/**
      - fix/**
      - fix/workflow-fixes-automerge

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-tests:
    uses: ./.github/workflows/shared/shared-tests.yml
    with:
      test_type: unit

  integration-tests:
    uses: ./.github/workflows/shared/shared-tests.yml
    with:
      test_type: integration

  security-tests:
    uses: ./.github/workflows/shared/shared-tests.yml
    with:
      test_type: security

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Biome check
        run: pnpm run biome check

      - name: Run tests
        run: pnpm --filter frontend test

  create-pr:
    needs: [unit-tests, integration-tests, security-tests, frontend-tests]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/fix/'))
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          title: "${{ env.BRANCH_NAME }}: ${{ github.event.head_commit.message }}"
          body: |
            ## Changes

            This PR was automatically created by the Feature Branch Push workflow.

            Commit: ${{ github.event.head_commit.message }}

            ### Checks
            - [ ] Tests pass
            - [ ] Code follows project standards
            - [ ] Documentation is updated
          labels: |
            automated-pr
            ${{ startsWith(github.ref, 'refs/heads/feat/') && 'feature' || 'fix' }}
          draft: false
