name: CI

on:
  push:
    branches: [ main, stg ]
  pull_request:
    branches: [ main, stg ]
  workflow_call:
    inputs:
      test_type:
        description: 'Type of tests to run (all, backend, frontend)'
        required: false
        type: string
        default: 'all'

permissions:
  contents: read

jobs:
  lint-backend:
    if: inputs.test_type == 'all' || inputs.test_type == 'backend' || inputs.test_type == ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        working-directory: backend
        run: uv pip install -e ".[dev,test]"

      - name: Run ruff linting
        working-directory: backend
        run: |
          uv run ruff check app
          uv run ruff format --check app

  lint-frontend:
    if: inputs.test_type == 'all' || inputs.test_type == 'frontend' || inputs.test_type == ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run biome linting
        run: pnpm run lint

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
    with:
      test_type: ${{ inputs.test_type || 'all' }}
      cache_dependencies: true
