apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: fastapi-app
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  SECRET_KEY: c3VwZXJzZWNyZXQ=
  FIRST_SUPERUSER_PASSWORD: c3VwZXJwYXNz
  SMTP_PASSWORD: c210cC1wYXNz
  SENTRY_DSN: ""
