name: GHCR Image Publishing

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Add environment suffix
        if: github.ref_name == 'dev'
        run: |
          echo "TAGS=$(echo '${{ steps.meta.outputs.tags }}' | sed 's/\(.*\)/\1-stg/')" >> $GITHUB_ENV

      - name: Set tags for main branch
        if: github.ref_name == 'main'
        run: |
          echo "TAGS=${{ steps.meta.outputs.tags }},ghcr.io/${{ github.repository }}:latest" >> $GITHUB_ENV

      - name: Set tags for dev branch
        if: github.ref_name == 'dev'
        run: |
          echo "TAGS=${{ env.TAGS }},ghcr.io/${{ github.repository }}:latest-stg" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TAGS || steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
