name: Security Scan

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/security.yml"
      - "backend/bandit.yaml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/security.yml"
      - "backend/bandit.yaml"
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety pip-audit

      - name: Run Bandit security scan
        run: bandit -c backend/bandit.yaml -r backend -f txt

      - name: Run Safety check
        run: safety check

      - name: Run pip-audit
        run: pip-audit
