name: Branch Protection

on:
  pull_request:
    branches:
      - main
      - stg

permissions:
  contents: read
  pull-requests: write

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR requirements
        run: |
          # Check if PR title follows convention
          if [ -z "${{ github.event.pull_request.title }}" ]; then
            echo "PR title is required"
            exit 1
          fi

          # Check if PR has required labels
          if [ -z "${{ github.event.pull_request.labels }}" ]; then
            echo "PR must have at least one label"
            exit 1
          fi

      - name: Check PR review requirements
        run: |
          # This step ensures that PR review requirements are enforced
          # GitHub already handles required reviews through branch protection rules
          echo "PR review requirements will be enforced by GitHub branch protection settings"
