name: Check Merge Path

on:
  pull_request:
    branches:
      - main

jobs:
  check-merge-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history to check branch relationships
      - name: Check if changes came through staging
        run: |
          # Get the merge base (common ancestor) of the PR branch and main
          MERGE_BASE=$(git merge-base ${{ github.event.pull_request.head.sha }} origin/main)
          echo "Merge base: $MERGE_BASE"

          # Get the latest stg commit that's part of this PR
          STG_COMMIT=$(git rev-list --first-parent origin/stg --until="${{ github.event.pull_request.head.sha }}" | head -n1)
          echo "Latest staging commit: $STG_COMMIT"

          if [ -z "$STG_COMMIT" ]; then
            echo "::error::Changes have not been merged through staging branch."
            echo "The proper flow is: feature -> stg -> main"
            exit 1
          fi

          # Check if staging commit is an ancestor of the PR
          if ! git merge-base --is-ancestor "$STG_COMMIT" "${{ github.event.pull_request.head.sha }}"; then
            echo "::error::Changes in this PR have not gone through the staging branch first."
            echo "The proper flow is: feature -> stg -> main"
            exit 1
          fi

          echo "✓ Changes have properly gone through staging branch"
