name: Deploy to Staging

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy-staging:
    name: Deploy to Staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      environment: staging
      image-tag: ${{ github.sha }}
      python-version: '3.11'
      node-version: '18'
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  test-pr:
    name: Test PR
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      environment: staging
      image-tag: pr-${{ github.event.pull_request.number }}
      python-version: '3.11'
      node-version: '18'
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
