name: Experimental PR Creation - Peter Evans

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Determine branch type
        id: branch-type
        run: |
          if [[ "${{ env.BRANCH_NAME }}" == feat/* ]]; then
            echo "TYPE=feat" >> $GITHUB_ENV
          elif [[ "${{ env.BRANCH_NAME }}" == fix/* ]]; then
            echo "TYPE=fix" >> $GITHUB_ENV
          else
            echo "TYPE=other" >> $GITHUB_ENV
          fi

      - name: Create Pull Request to staging
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: stg
          title: "${{ env.TYPE }}: ${{ env.BRANCH_NAME }}"
          body: |
            ## Automated PR from ${{ env.BRANCH_NAME }}

            This PR was automatically created from branch `${{ env.BRANCH_NAME }}`.

            Branch type: `${{ env.TYPE }}`

            ### Changes

            <!-- Please describe the changes made in this PR -->

            ### Checklist

            - [ ] Tests added/updated
            - [ ] Documentation updated
            - [ ] Linting passes
            - [ ] Security checks pass
          labels: |
            automated-pr
            ${{ env.TYPE }}
          draft: false

      - name: PR Details
        if: steps.create-pr.outputs.pull-request-number
        run: |
          echo "PR #${{ steps.create-pr.outputs.pull-request-number }} created: ${{ steps.create-pr.outputs.pull-request-url }}"
