name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feat/**'

# Add permissions needed for PR creation
permissions:
  contents: write
  pull-requests: write

jobs:
  fast-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install uv
        run: |
          pip install 'uv==0.4.15'

      - name: Install backend dependencies
        run: |
          cd backend
          if [ -f "requirements.txt" ]; then
            uv pip install -r requirements.txt
          else
            uv pip install .
          fi

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run backend unit tests
        run: |
          cd backend
          pytest -xvs app/tests/

      - name: Run frontend tests
        run: |
          cd frontend
          npm test || echo "No frontend tests available"

      - name: Run linting
        run: |
          cd backend
          flake8 app
          black --check app

  deploy-staging:
    needs: fast-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fastapi-project-app
          IMAGE_TAG: staging-${{ github.sha }}
        run: |
          docker-compose build
          docker tag fastapi-project-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to ECS staging
        run: |
          aws ecs update-service --cluster fastapi-staging --service fastapi-service --force-new-deployment

  auto-pr:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Automated PR from feature branch"
          title: "Feature: ${{ github.ref_name }}"
          body: |
            ## Feature Branch PR

            This PR was automatically created from the feature branch: ${{ github.ref_name }}

            ### Changes included:
            ${{ github.event.head_commit.message }}
          branch: ${{ github.ref_name }}
          base: main
          labels: feature
