name: Feature Branch Checks

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'

jobs:
  style-checks:
    name: Style and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.15"
          enable-cache: true

      - name: Install Python dependencies
        run: |
          uv pip install black flake8 bandit pip-audit
        working-directory: backend

      - name: Run black
        run: black --check .
        working-directory: backend

      - name: Run flake8
        run: flake8 .
        working-directory: backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: frontend

      - name: Run Prettier
        run: npm run format:check
        working-directory: frontend

  security-checks:
    name: Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.15"
          enable-cache: true

      - name: Install Python dependencies
        run: |
          uv pip install bandit pip-audit
        working-directory: backend

      - name: Run Bandit
        run: bandit -r .
        working-directory: backend

      - name: Run pip-audit
        run: pip-audit
        working-directory: backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Run npm audit
        run: npm audit
        working-directory: frontend

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      environment: test
      image-tag: ${{ github.sha }}
      python-version: '3.11'
      node-version: '18'
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
