name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feat/**'

# Add permissions needed for PR creation
permissions:
  contents: write
  pull-requests: write

jobs:
  fast-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install 'uv==0.4.15'

      - name: Install backend dependencies
        run: |
          cd backend
          if [ -f "requirements.txt" ]; then
            python -m uv pip install --system -r requirements.txt
          else
            python -m uv pip install --system .
          fi

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run backend unit tests
        run: |
          cd backend
          pytest -xvs app/tests/

      - name: Run frontend tests
        run: |
          cd frontend
          npm test || echo "No frontend tests available"

      - name: Run linting
        run: |
          cd backend
          flake8 app
          black --check app

  deploy-staging:
    needs: fast-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          IMAGE_TAG=staging-${{ github.sha }}
          docker-compose build
          docker tag fastapi-project-app:latest ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app:$IMAGE_TAG

      - name: Push Docker Image to GHCR
        run: |
          IMAGE_TAG=staging-${{ github.sha }}
          docker push ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app:$IMAGE_TAG

      - name: Deploy to staging environment
        run: |
          echo "Deployed to staging environment with image: ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app:staging-${{ github.sha }}"

  auto-pr:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure we have the token for PR creation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Automated PR from feature branch"
          title: "Feature: ${{ github.ref_name }}"
          body: |
            ## Feature Branch PR

            This PR was automatically created from the feature branch: ${{ github.ref_name }}

            ### Changes included:
            ${{ github.event.head_commit.message }}
          branch: create-pull-request/patch
          base: main
          labels: feature
          delete-branch: false

      - name: Check outputs
        if: steps.create-pr.outputs.pull-request-number
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
