name: Formatting

on:
  workflow_call:
    inputs:
      target:
        description: 'Target to format (backend, frontend, or all)'
        required: true
        type: string
        default: 'all'

permissions:
  contents: write

jobs:
  backend-format:
    if: inputs.target == 'backend' || inputs.target == 'all'
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "backend/requirements**.txt"

      - name: Install ruff
        working-directory: backend
        run: uv pip install --upgrade ruff

      - name: Format Python code
        working-directory: backend
        run: |
          ruff format .
          ruff check --fix .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format Python code with ruff"
          file_pattern: 'backend/**/*.py'

  frontend-format:
    if: inputs.target == 'frontend' || inputs.target == 'all'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Format frontend code
        working-directory: frontend
        run: |
          pnpm install
          pnpm biome check --apply-unsafe src/ tests/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format frontend code with Biome"
          file_pattern: 'frontend/**/*.(js|jsx|ts|tsx|json)'
