name: Generate API Client

on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:
      - main
      - dev

jobs:
  generate-client:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}

    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.4.15"
        enable-cache: true

    - name: Install frontend dependencies
      run: npm ci
      working-directory: frontend

    - name: Install backend dependencies
      run: uv sync
      working-directory: backend

    - name: Generate client
      run: uv run bash scripts/generate-client.sh
      env:
        VIRTUAL_ENV: backend/.venv
        ENVIRONMENT: development
        SECRET_KEY: temp-key-for-client-generation
        POSTGRES_PASSWORD: temp-password-for-client-generation
        FIRST_SUPERUSER_PASSWORD: temp-password-for-client-generation

    - name: Commit changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add frontend/src/client
        git diff --staged --quiet || git commit -m "📚 Update API client"

    - name: Push changes
      if: github.event.pull_request.head.repo.full_name == github.repository
      run: git push
