name: Main Branch Workflow

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  packages: write

jobs:
  check-conditions:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
      should_run_tests: true
    steps:
      - name: Check workflow conditions
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "PR was merged to main, proceeding with deployment"
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "opened" || \
                 "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "synchronize" || \
                 "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "reopened" ]]; then
            echo "PR was created or updated, running tests"
            echo "should_run_tests=true" >> $GITHUB_OUTPUT
          else
            echo "Not a merged PR to main, skipping deployment"
          fi

  lint:
    runs-on: ubuntu-latest
    needs: check-conditions
    if: needs.check-conditions.outputs.should_run_tests == 'true'
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python and Node.js
        run: |
          apt-get update && apt-get install -y \
            curl \
            gnupg \
            python3.10 \
            python3.10-venv \
            python3-pip \
            && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
            && apt-get install -y nodejs \
            && npm install -g pnpm@10.6.4 \
            && pip3 install --no-cache-dir uv \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/*

      - name: Cache UV packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            backend/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/pyproject.toml', 'pnpm-lock.yaml', 'backend/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: make install

      - name: Install frontend dependencies
        run: cd frontend && pnpm install --frozen-lockfile

      - name: Run linting
        run: make lint

  security-scan:
    runs-on: ubuntu-latest
    needs: check-conditions
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python and Node.js
        run: |
          apt-get update && apt-get install -y \
            curl \
            gnupg \
            python3.10 \
            python3.10-venv \
            python3-pip \
            && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
            && apt-get install -y nodejs \
            && npm install -g pnpm@10.6.4 \
            && pip3 install --no-cache-dir uv \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/*

      - name: Cache UV packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            backend/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/pyproject.toml', 'pnpm-lock.yaml', 'backend/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: make install

      - name: Install frontend dependencies
        run: cd frontend && pnpm install --frozen-lockfile

      - name: Run security scan
        run: make security-scan

  test:
    needs: [lint, security-scan, check-conditions]
    if: needs.check-conditions.outputs.should_run_tests == 'true'
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "FastAPI Project"
      POSTGRES_SERVER: "localhost"
      POSTGRES_USER: ${{ secrets.POSTGRES_USER || 'postgres' }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD || 'postgres' }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB || 'app' }}
      FIRST_SUPERUSER: "admin@example.com"
      FIRST_SUPERUSER_PASSWORD: "adminpass123"
      EMAILS_ENABLED: "True"
      SMTP_HOST: "localhost"
      SMTP_PORT: "25"
      SMTP_USER: "test@example.com"
      SMTP_PASSWORD: "testpassword"
      EMAILS_FROM_EMAIL: "test@example.com"
      SECRET_KEY: "testing_secret_key_for_ci"
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER || 'postgres' }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD || 'postgres' }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB || 'app' }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres && psql -U postgres -d app -c 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache UV packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            backend/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/pyproject.toml', 'pnpm-lock.yaml', 'backend/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.4
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: |
            ./backend/coverage.xml
            ./frontend/coverage/coverage-final.json
          flags: |
            backend
            frontend
          name: coverage-report

  semantic-release:
    needs: [test, security-scan, check-conditions]
    if: needs.check-conditions.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.4
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release

  publish-images:
    needs: [semantic-release, check-conditions]
    if: needs.check-conditions.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.4
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(pnpm exec node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/datascientest-fastapi-project-group-25/backend:${{ steps.get_version.outputs.version || 'latest' }}
            ghcr.io/datascientest-fastapi-project-group-25/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/datascientest-fastapi-project-group-25/frontend:${{ steps.get_version.outputs.version || 'latest' }}
            ghcr.io/datascientest-fastapi-project-group-25/frontend:latest
          build-args: |
            VITE_API_URL=http://localhost:8000
            NODE_ENV=production
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify image publication
        run: |
          echo "Published Docker images to GHCR: \
            ghcr.io/datascientest-fastapi-project-group-25/backend:${{ steps.get_version.outputs.version || 'latest' }} \
            ghcr.io/datascientest-fastapi-project-group-25/frontend:${{ steps.get_version.outputs.version || 'latest' }}"
          echo "These images are now available for deployment by the infrastructure repository."
