name: Main Branch Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  full-test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install uv
        run: |
          pip install 'uv==0.4.15'

      - name: Install backend dependencies
        run: |
          cd backend
          if [ -f "requirements.txt" ]; then
            uv pip install -r requirements.txt
          else
            uv pip install .
          fi

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          pytest -xvs app/tests/

      - name: Run frontend tests
        run: |
          cd frontend
          npm test || echo "No frontend tests available"

      - name: Run linting
        run: |
          cd backend
          flake8 app
          black --check app

      - name: Run security scans
        run: |
          cd backend
          uv pip install bandit
          bandit -r app -x app/tests

          cd ../frontend
          npm audit || echo "Vulnerabilities found, but continuing"

      - name: Run integration tests
        run: |
          docker-compose -f docker-compose.test.yml up \
            --build --exit-code-from backend-tests

  semantic-release:
    needs: full-test-suite
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  deploy-production:
    needs: semantic-release
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and Tag Docker Image
        run: |
          IMAGE_TAG=${{ steps.get_version.outputs.version || 'latest' }}
          docker-compose build
          docker tag fastapi-project-app:latest \
            ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app:$IMAGE_TAG
          docker tag fastapi-project-app:latest \
            ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app:latest

      - name: Push Docker Image to GHCR
        run: |
          IMAGE_TAG=${{ steps.get_version.outputs.version || 'latest' }}
          docker push \
            ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app:$IMAGE_TAG
          docker push \
            ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app:latest

      - name: Deploy to production environment
        run: |
          echo "Deployed to production environment with image: \
            ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app:${{ steps.get_version.outputs.version || 'latest' }}"
