name: Merge to Staging

on:
  push:
    branches: [stg]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push staging images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner | lower }}/${{ github.event.repository.name | lower }}:staging
          target: staging
          cache-from: type=gha,scope=staging
          cache-to: type=gha,mode=max,scope=staging

      - name: Deploy to staging
        run: |
          docker compose -f docker-compose.yml -f docker-compose.staging.yml pull
          docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d

      - name: Health check
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8000/api/health; then
              exit 0
            fi
            sleep 5
          done
          exit 1

      - name: Create PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-pr-to-main
          title: 'chore: Automatic PR from staging to main'
          body: 'Automatically created PR to merge changes from staging to main'
          labels: 'auto-pr'
          draft: true
