name: Playwright Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
    - opened
    - synchronize
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed == 'true' }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          changed:
            - backend/**
            - frontend/**
            - .env
            - docker-compose*.yml
            - .github/workflows/playwright.yml

  test-playwright:
    needs: changes
    if: ${{ needs.changes.outputs.changed }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.11"
        enable-cache: true
    - name: Install backend dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync
      working-directory: backend
    - name: Install frontend dependencies
      run: npm ci
      working-directory: frontend
    - name: Generate client
      run: |
        source .venv/bin/activate
        bash scripts/generate-client.sh
      working-directory: backend
    - name: Build test containers
      run: docker compose -f docker-compose.test.yml build
    - name: Run Playwright tests
      run: |
        docker compose -f docker-compose.test.yml down -v --remove-orphans
        docker compose -f docker-compose.test.yml run --rm test-playwright npx playwright test --fail-on-flaky-tests --trace=retain-on-failure --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        docker compose -f docker-compose.test.yml down -v --remove-orphans
    - name: Upload blob report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: frontend/blob-report
        retention-days: 7

  merge-reports:
    needs: [test-playwright, changes]
    if: always() && needs.changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    - name: Download reports
      uses: actions/download-artifact@v4
      with:
        path: frontend/all-blob-reports
        pattern: blob-report-*
        merge-multiple: true
    - name: Merge reports
      run: npx playwright merge-reports --reporter html ./all-blob-reports
      working-directory: frontend
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: frontend/playwright-report
        retention-days: 30

  check-status:
    if: always()
    needs: [test-playwright]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: test-playwright
