name: Reusable PR Creation

on:
  workflow_call:
    inputs:
      source_branch:
        required: true
        type: string
      target_branch:
        required: true
        type: string
      pr_title:
        required: true
        type: string
      pr_body:
        required: true
        type: string
      pr_label:
        required: false
        type: string
    secrets:
      MACHINE_USER_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or Update Pull Request
        id: create-pr
        env:
          GH_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
        run: |
          echo "Promoting '${{ inputs.source_branch }}' into '${{ inputs.target_branch }}'"
          echo "Source branch: ${{ inputs.source_branch }}"
          echo "Target branch: ${{ inputs.target_branch }}"

          existing_pr_url=$(gh pr list --head "${{ inputs.source_branch }}" --base "${{ inputs.target_branch }}" --state open --json url --jq '.[0].url')

          if [ -n "$existing_pr_url" ]; then
            echo "Pull request already exists: $existing_pr_url"
            pr_url="$existing_pr_url"
            pr_number=$(basename "$pr_url" | cut -d'/' -f1)
            echo "pull-request-url=$pr_url" >> $GITHUB_OUTPUT
            echo "pull-request-number=$pr_number" >> $GITHUB_OUTPUT
          else
            pr_url=$(gh pr create \
              --base "${{ inputs.target_branch }}" \
              --head "${{ inputs.source_branch }}" \
              --title "${{ inputs.pr_title }}" \
              --body "${{ inputs.pr_body }}")
            echo "PR URL: $pr_url"
            pr_number=$(basename "$pr_url" | cut -d'/' -f1)
            echo "pull-request-url=$pr_url" >> $GITHUB_OUTPUT
            echo "pull-request-number=$pr_number" >> $GITHUB_OUTPUT
          fi

          echo "pr_number=$pr_number" >> $GITHUB_ENV

      - name: Add PR Label
        if: ${{ inputs.pr_label != '' }}
        env:
          GH_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
        run: |
          echo "Adding label '${{ inputs.pr_label }}' to PR #${{ env.pr_number }}"
          gh pr edit ${{ env.pr_number }} --add-label "${{ inputs.pr_label }}"

      - name: PR Details
        if: success()
        run: |
          echo "PR created or already exists."
