name: Promote stg to main on PR merge

on:
  pull_request:
    types: [closed]
    branches:
      - stg

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract source branch and PR info
        shell: bash
        run: |
          echo "SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_BODY=${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Delete source branch
        run: |
          echo "Attempting to delete branch: ${SOURCE_BRANCH}"
          if gh api repos/${{ github.repository }}/git/refs/heads/${SOURCE_BRANCH} > /dev/null 2>&1; then
            gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${SOURCE_BRANCH}
            echo "Branch deleted."
          else
            echo "Branch does not exist or already deleted, skipping."
          fi
        env:
          GH_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}

      - name: Create Pull Request from stg to main
        id: create-pr
        uses: devops-infra/action-pull-request@v0.5.4
        with:
          github_token: ${{ secrets.MACHINE_USER_TOKEN }}
          source_branch: stg
          target_branch: main
          title: "Promote staging to main: #${{ env.PR_NUMBER }} - ${{ env.PR_TITLE }}"
          body: |
            Automated PR to promote changes from **stg** to **main**.

            Original PR #${{ env.PR_NUMBER }}:

            ${{ env.PR_BODY }}

      - name: PR Details
        if: steps.create-pr.outputs.pull-request-number
        run: |
          echo "PR #${{ steps.create-pr.outputs.pull-request-number }} created: ${{ steps.create-pr.outputs.pull-request-url }}"
