name: Push Docker Image to GHCR

on:
  push:
    branches:
      - main
      - dev
      - 'feat/**'
      - 'fix/**'

jobs:
  push-to-ghcr:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Backend image
      - name: Extract metadata for Backend Docker
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app-backend
          tags: |
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      # Frontend image
      - name: Extract metadata for Frontend Docker
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app-frontend
          tags: |
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
