name: Security Scan

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/security.yml"
      - "backend/bandit.yaml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/security.yml"
      - "backend/bandit.yaml"
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety pip-audit

      - name: Run Bandit security scan
        run: bandit -c backend/bandit.yaml -r backend -f json -o results.json

      - name: Upload Bandit scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.json
          category: bandit
          checkout_path: ${{ github.workspace }}

      - name: Run Safety check
        run: safety check

      - name: Run pip-audit
        run: pip-audit
