name: Security Scan

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/security.yml"
      - "backend/bandit.yaml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/security.yml"
      - "backend/bandit.yaml"
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          pip install -r backend/requirements.txt

      - name: Run Bandit security scan
        run: |
          bandit -c backend/bandit.yaml -r backend -f sarif -o results.sarif

      - name: Upload Bandit scan results
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
          category: bandit

      - name: Run Safety check
        run: |
          safety check -r backend/requirements.txt --full-report

      - name: Run pip-audit
        run: |
          pip install pip-audit
          pip-audit -r backend/requirements.txt
