name: CD - Auto-PR Staging to Main Branch

on:
  pull_request:
    types: [closed]
    branches:
      - stg

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          fetch-depth: 0

      - name: Set up git merge drivers
        run: |
          chmod +x ./scripts/setup-git-hooks.sh
          ./scripts/setup-git-hooks.sh
          echo "Git merge drivers set up successfully"

      - name: Get version
        id: get-version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Create PR to main
        uses: ./.github/actions/create-pr
        with:
          source_branch: stg
          target_branch: main
          pr_title: "release(prod): v${{ steps.get-version.outputs.version }}"
          pr_body: |
            # Promote Staging to Main

            This PR promotes changes from staging to main.

            ## Original Changes

            Original PR:

            ${{ github.event.pull_request.body }}
          pr_label: promote-to-main
          github_token: ${{ secrets.MACHINE_USER_TOKEN }}
