name: Test Docker Compose

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build test containers
        run: docker compose -f docker-compose.test.yml build

      - name: Remove existing containers
        run: docker compose -f docker-compose.test.yml down -v --remove-orphans

      - name: Start test services
        run: docker compose -f docker-compose.test.yml up -d --wait test-db test-backend test-frontend

      - name: Test backend health
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8001/api/v1/utils/health-check; then
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: Test frontend availability
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:5174; then
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yml down -v --remove-orphans
