name: Tests

on:
  workflow_call:
    inputs:
      test_type:
        description: 'Type of tests to run (backend-unit, backend-integration, backend-e2e, frontend-unit, frontend-integration, frontend-e2e)'
        required: true
        type: string
      cache_dependencies:
        description: 'Whether to cache dependencies'
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  backend-tests:
    if: startsWith(inputs.test_type, 'backend-')
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10
          --health-start-period 5s
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      PROJECT_NAME: FastAPI
      POSTGRES_SERVER: localhost
      POSTGRES_USER: postgres
      FIRST_SUPERUSER: admin@example.com
      FIRST_SUPERUSER_PASSWORD: password
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Cache uv directory
        if: inputs.cache_dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            backend/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/requirements*.txt', 'backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        working-directory: backend
        run: uv venv --system-site-packages && uv pip install -e ".[dev,lint,types,test]"

      - name: Wait for PostgreSQL
        working-directory: backend
        run: |
          uv run python -c "import time, psycopg; \
          for i in range(30): \
              try: \
                  conn = psycopg.connect('postgresql://postgres:postgres@localhost:5432/test_db'); \
                  conn.close(); \
                  print('PostgreSQL is ready!'); \
                  break; \
              except Exception as e: \
                  if i == 29: raise e; \
                  print(f'Waiting for PostgreSQL: {e}'); \
                  time.sleep(1);"

      - name: Run backend unit tests
        if: inputs.test_type == 'backend-unit'
        working-directory: backend
        run: uv run pytest --cov=app --cov-report=xml

      - name: Run backend integration tests
        if: inputs.test_type == 'backend-integration'
        working-directory: backend
        run: uv run pytest -m integration --cov=app --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage.xml

  frontend-tests:
    if: startsWith(inputs.test_type, 'frontend-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        if: inputs.cache_dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run frontend unit tests
        if: inputs.test_type == 'frontend-unit'
        run: pnpm --filter frontend test

      - name: Run frontend E2E tests
        if: inputs.test_type == 'frontend-e2e'
        run: pnpm --filter frontend playwright test
