name: Update PR Title with Type

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main # Or your primary integration branches like 'stg', 'develop' etc.
      - stg  # Add staging branch

permissions:
  pull-requests: write # Needed to update the PR title

jobs:
  update-title:
    runs-on: ubuntu-latest
    # Only run on PRs from conventional commit type branches within the same repo
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      (startsWith(github.head_ref, 'feat/') ||
       startsWith(github.head_ref, 'fix/') ||
       startsWith(github.head_ref, 'docs/') ||
       startsWith(github.head_ref, 'style/') ||
       startsWith(github.head_ref, 'refactor/') ||
       startsWith(github.head_ref, 'perf/') ||
       startsWith(github.head_ref, 'test/') ||
       startsWith(github.head_ref, 'build/') ||
       startsWith(github.head_ref, 'ci/') ||
       startsWith(github.head_ref, 'chore/') ||
       startsWith(github.head_ref, 'revert/'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Type Prefix
        id: determine-prefix
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          TARGET_BRANCH: ${{ github.base_ref }}
        run: |
          chmod +x .github/scripts/format-pr-title.sh
          PREFIX=$(.github/scripts/format-pr-title.sh "$BRANCH_NAME" "$TARGET_BRANCH" | cut -d' ' -f1)
          echo "prefix=$PREFIX:" >> $GITHUB_OUTPUT
          echo "Determined prefix: $PREFIX:"

      - name: Update PR Title
        uses: actions/github-script@v7
        env:
          PREFIX: ${{ steps.determine-prefix.outputs.prefix }}
        with:
          # Using the default GITHUB_TOKEN which usually has pull-requests: write permission
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prefix = process.env.PREFIX;
            const prNumber = context.issue.number;
            const prTitle = context.payload.pull_request.title;

            // Check if title already starts with a conventional commit type (e.g., feat:, fix:, chore:, etc.)
            const ccRegex = /^(feat|fix|build|chore|ci|docs|perf|refactor|revert|style|test)(\(.*\))?!?:/;
            if (ccRegex.test(prTitle)) {
              console.log('PR title already has a conventional commit type prefix. Skipping update.');
              return;
            }

            // Check if title already starts with the determined prefix (idempotency)
            if (prTitle.startsWith(prefix)) {
              console.log(`PR title already starts with '${prefix}'. Skipping update.`);
              return;
            }

            // Prepend the prefix
            const newTitle = `${prefix} ${prTitle}`;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              title: newTitle
            });

            console.log(`Updated PR title to: ${newTitle}`);
